[package]
name = "Tcp-Ping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true

[dependencies]
termcolor = "1.3.0"
winapi = "0.3.9"